-   id: generate-changelog
    name: generate changelog from folder
    entry: generate-changelog
    language: python
    minimum_pre_commit_version: '3.7.1'
    language_version: python3
    files: ^(changelog|changelogs)/.*\.(yml|yaml)$
    types: [yaml]
    stages: [commit, push, manual]
