-   id: generate-changelog
    name: generate changelog from folder
    entry: generate-changelog
    language: python
    additional_dependencies: [pre-commit-hooks-changelog]
    files: ^(changelog|changelogs)/.*\.(yml|yaml)$
    types: [yaml]
    stages: [commit, push, manual]
