blank_issues_enabled: false
contact_links:
    -   name: Documentation
        url: https://github.com/chrysa/pre-commit-hooks-changelog#readme
        about: Read the project documentation
    -   name: Discussions
        url: https://github.com/chrysa/pre-commit-hooks-changelog/discussions
        about: Ask a question or discuss the project
